### ISSUE TITLE
Dev: Content/ Tools/ Structure

### ISSUE THREAD

**Issue by mart0855** [mart0855/non-profit-website#10]
@coll0335 
- [x] Finalize chosen tools that you plan to implement on your website (js libraries, jQuery plugins, etc)
- [x] Finished branding assets/ site content (what content is going on each page)
- [x] Streamline content
- [x] Update menus and site structure/content based on usability testing

**Comment by coll0335** [comment]
I listed some of the tools that I know we will need for the website. However, if I missed something, feel free to add it or let me know

Also, as for streamlining the content I think Gabe already finished that. As for the Menu what were the results of the Usability Testing?
