### ISSUE TITLE
Dev: Iconic Font/ Folder Structure

### ISSUE THREAD

**Issue by mart0855** [mart0855/non-profit-website#16]
- [x] Using the icons provided by the Design Team and demonstrated in your wireframes, create a iconic font that includes all the icons on your site
- [x] Set up repository for final site, with gh-pages branch
- [x] Create folder structure for SCSS files, and Jekyll templates in that folder
- You will only be expected to template your header and footer for this project, however you are welcome to add more templates

**Comment by coll0335** [comment]
Still need the icons
