### ISSUE TITLE
Donate page styling

### ISSUE THREAD

**Issue by mart0855** [mart0855/non-profit-website#25]
I converted donate to gh-pages to become most recent iteration. Some styling issues arise on the donation page when viewed in the browser which differ from viewing in terminal...

![radio-buttons](https://cloud.githubusercontent.com/assets/6333794/6547314/d8c20626-c5aa-11e4-9fd6-dc94f8cd37c5.jpg)
![proceed-btn](https://cloud.githubusercontent.com/assets/6333794/6547325/0ae58b1e-c5ab-11e4-81df-93e51e28719f.jpg)

**Comment by alkalinegenome** [comment]
Alex, which browser did you view this on?, is it ongoing? and is it replicable? Both Desktop Chrome & Safari work as they should. Android Tablets & Smartphones work as they should. 

Firefox & IE are the ones malfunctioning, but not as indicated in your screenie. The selected bar doesn't show, and only the ugly radio button shows.

This looks like the CSS wasn't even loaded at all. The forms, and the buttons have been styled

**Comment by mart0855** [comment]
It is working fine since you merged "origin/gh-pages"
